import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { LogOut, User, Activity, Bell } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import PatientList from '../components/PatientList';
export default function Dashboard() {
    const { user, logout } = useAuth();
    const navigate = useNavigate();
    function handleLogout() {
        logout();
        navigate('/login');
    }
    return (_jsxs("div", { className: "min-h-screen bg-slate-50 flex flex-col", children: [_jsxs("nav", { className: "bg-white border-b border-slate-200 h-16 flex items-center justify-between px-6 sticky top-0 z-10 shadow-sm", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-9 h-9 bg-blue-600 rounded-lg flex items-center justify-center shadow-md shadow-blue-100", children: _jsx(Activity, { className: "text-white w-5 h-5" }) }), _jsx("h1", { className: "text-lg font-bold text-slate-900 hidden sm:block", children: "MedCore Dashboard" })] }), _jsx("div", { className: "flex-1 max-w-md mx-8 hidden md:block" }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("button", { className: "p-2 text-slate-500 hover:bg-slate-100 rounded-full transition-colors relative", children: [_jsx(Bell, { className: "w-5 h-5" }), _jsx("span", { className: "absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full border-2 border-white" })] }), _jsx("div", { className: "h-8 w-px bg-slate-200 mx-1" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "text-right hidden sm:block", children: [_jsx("p", { className: "text-sm font-semibold text-slate-900 leading-none", children: user?.name }), _jsx("p", { className: "text-xs text-slate-500 mt-1 capitalize", children: user?.role.toLowerCase() })] }), _jsx("div", { className: "w-10 h-10 bg-slate-200 rounded-full flex items-center justify-center overflow-hidden border-2 border-white shadow-sm", children: _jsx(User, { className: "text-slate-500 w-6 h-6" }) }), _jsx("button", { onClick: handleLogout, className: "p-2 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded-full transition-all", title: "Logout", children: _jsx(LogOut, { className: "w-5 h-5" }) })] })] })] }), _jsx("main", { className: "flex-1 container mx-auto py-8 px-6", children: _jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.4 }, children: [_jsx("div", { className: "flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8", children: _jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900", children: "Patient Overview" }), _jsx("p", { className: "text-slate-500 mt-1", children: "Manage and track your patient records efficiently." })] }) }), _jsx("div", { className: "bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden", children: _jsx(PatientList, {}) })] }) }), _jsxs("footer", { className: "py-6 px-6 border-t border-slate-200 bg-white text-center text-slate-400 text-sm", children: ["Made with \u2764\uFE0F by ", _jsx("a", { className: 'hover:text-slate-500', href: "https://www.linkedin.com/in/rohitjoshihere/", target: "_blank", rel: "noopener noreferrer", children: "Rohit" })] })] }));
}
